languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "mykmal"
copyright = "© 2023 Mykhaylo Malakhov"

[params]
  dateFormat = "January 2, 2006"

  # mainSections = ["section1", "section2"]
  description = "Biostatistics PhD student. I develop statistical and machine learning methods to help uncover the genetic causes underlying neurodegenerative diseases."

[author]
  name = "Mykhaylo M. Malakhov"
  image = "img/mykmal.jpg"
  headline = "Solving neurodegeneration with genetics + ML."
  bio = "I am a PhD student in the Division of Biostatistics and Health Data Science at the University of Minnesota School of Public Health. My research focuses on developing statistical and machine learning methods for analyzing genomic data, with the ultimate goal of uncovering the genetic causes and biological processes underlying neurodegenerative diseases."
  links = [
    { linkedin = "https://linkedin.com/in/mykmal" },
    { github = "https://github.com/mykmal" },
    { orcid = "https://orcid.org/0000-0002-6856-3913" },
    { email = "mailto:mykhaylomalakhov@gmail.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { x-twitter = "https://twitter.com/username" },
  #   { youtube = "https://youtube.com/username" },
  ]
