[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.136.2"
  NODE_ENV = "production"
  TZ = "America/Chicago"  # Set to preferred timezone

[context.production.environment]
  HUGO_ENV = "production"
