[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.120.3"
  NODE_ENV = "production"
  TZ = "UTC-5"  # Set to preferred timezone

[context.production.environment]
  HUGO_ENV = "production"
